[package]
name = "cyan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
    "sync"
] }
clap = { version = "4.5.4", features = ["derive"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
chrono = "0.4.38"
nestify = "0.3.3"
figment = { version = "0.10.19", features = ["env", "toml"] }
serde = { version = "1.0.203", features = ["derive"] }
dirs = "5.0.1"
lazy_static = "1.4.0"

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.8.1", features = [
    "tokio",
    "wayland",
], default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
tray-item = "0.10.0"
notify = "6.1.1"
known-folders = "1.1.0"

[build-dependencies]
embed-resource = "2.3"
