[package]
name = "cyan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
    "time"
] }
clap = { version = "4.5.4", features = ["derive"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
chrono = "0.4.38"

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.8.1", features = [
    "tokio",
    "wayland",
], default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-win = {version = "5.3.1", features = ["monitor"]}
image = "0.25.1"