[package]
name = "cyan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
    "sync"
] }
clap = { version = "4.5.4", features = ["derive"] }
# sqlite = { version = "0.36.0", features = ["bundled"] }
# rusqlite = { version = "0.31.0", features = ["bundled"] }
chrono = "0.4.38"
nestify = "0.3.3"
figment = { version = "0.10.19", features = ["env", "toml"] }
serde = { version = "1.0.203", features = ["derive"] }
dirs = "5.0.1"
lazy_static = "1.4.0"
glob = "0.3.1"
gxhash = { version = "3.4.1", features = ["hybrid"] }
# serde_rusqlite = "0.35.0"
filetime = "0.2.23"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio", "tls-rustls"] }

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.8.1", features = [
    "tokio",
    "wayland",
], default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
tray-item = "0.10.0"
notify = "6.1.1"
known-folders = "1.1.0"

[build-dependencies]
embed-resource = "2.3"
